modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile = "vibranium_title.png"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="jei"
type="optional"
versionRange="${jei_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="rei"
type="optional"
versionRange="${rei_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="cloth_config"
type="optional"
versionRange="${cloth_config_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="architectury"
type="optional"
versionRange="${architectury_version_range}"
ordering="NONE"
side="BOTH"
